### ISSUE TITLE
Text to speech converter 

### ISSUE THREAD

**Issue by Gaurav0203Shetty** [Open-Source-you/Hackotberfest2024#183]
A text to speech converter using HTML, CSS and JS

**Comment by Zahhiiir** [comment]
Hi @Gaurav0203Shetty  I would love to contribute this issue under hacktoberfest , please assign this issue to me with respective tags.

**Comment by Gaurav0203Shetty** [comment]
Hey @Zahhiiir , i am working on it myself. i created this issue for it to be assigned to me.
