### ISSUE TITLE
html normal website 

### ISSUE THREAD

**Issue by Open-Source-you** [Open-Source-you/Hackotberfest2024#86]

**Comment by Dorcastunmise** [comment]
Hello @Open-Source-you , can you describe the issue? Please

**Comment by anuragitme** [comment]
@Open-Source-you can you assign this issue to me

**Comment by Dorcastunmise** [comment]
Ooohh..... @anuragitme goodluck.

**Comment by Open-Source-you** [comment]
@Dorcastunmise If you have interest then you can work on this  issue.  Add All project in One Website(like,card game,calc...) #6

**Comment by Open-Source-you** [comment]
@Dorcastunmise  Should I assign you is this the issue?? #6

**Comment by Ridham32** [comment]
hi @Open-Source-you can u assign this project to me?

**Comment by ayushrakesh** [comment]
Can you assign this problem to me ?
